apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deploy
  labels:
    name: gateway-deploy
    app: microservice
spec:
 replicas: 1
 selector:
  matchLabeles:
    app: gateway
    type: microservice
template:
   metadata: 
    name: gateway-pod
    labels:
        app: gateway
        type: microservice
    spec:
        containers:
            - name: gateway-app
              image: datus34/serviciosapigateway:latest
              ports:
                - containePort: 80

