apiVersion: v1
kind: Pod
metadata: 
    name:  microservice-seguridad-pod
    labels:
        app: microservice-seguridad
        type: microservice
spec:
    containers:
        - name: microservice-seguridad-app
          image: datus34/serviciosapiseguridad:latest
          ports:
            - containePort: 80
          env:
           - name: ConnectionStrings__ConexionDB
             value: Server=mssql-service;Database=Seguridad;User=sa;Password=dquesada#4_2024

