apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deploy
  labels:
    name: mongo-deploy
    app: microservice-libreria
spec:
 replicas: 1
 selector:
  matchLabels:
   app: microservice-libreria
   name: mongo-pod
 template:
  metadata: 
    labels:
        app: microservice-libreria
        name: mongo-pod
  spec:
   containers:
      - name: mongo
        image: mongo:4.2.12
        command: 
        - /bin/bash
        - -c
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "dquesada"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "dquesada#4_2024"
        ports:
        - containerPort: 27017    